### ISSUE TITLE
README.md review

### ISSUE THREAD

**Issue by loganstone** [Taeho-Kang/minitwitter#4]
e9e5824104442d8fab760a9dc4a6fd10d47f7663 를 확인하고, MariaDB, MongoDB 중 하나를 선택하여 피드백을 주세요.

=> 몽고DB(NoSQl) 맞지?

**Comment by Taeho-Kang** [comment]
MongoDB(NoSQL)로 결정

**Comment by loganstone** [comment]
DB 가 결정 되어 해당 이슈를 닫음
